import xara
import xara.units.iks as units
import math
import numpy as np
import pandas as pd
from mdof.utilities.config import extract_channels
import csv
import os
import cvxpy as cp 
import tqdm
import plotly.graph_objects as go
from pathlib import Path

def ReinforcedRectangle(model, id, h, b, cover, coreID, coverID, steelID, numBars, barArea, nfCoreY, nfCoreZ, nfCoverY, nfCoverZ, GJ):
    r"""
    Define a procedure which generates a rectangular reinforced concrete section
    with one layer of steel evenly distributed around the perimeter and a confined core.

                          y
                          |
                          |
                          |
                ---------------------
                |\                 /|
                | \---------------/ |
                | |               | |
                | |               | |
     z ---------| |               | |  h
                | |               | |
                | |               | |
                | /---------------\ |
                |/                 \|
                ---------------------
                          b

    Arguments
       id - tag for the section that is generated by this procedure
       h - overall height of the section (see above)
       b - overall width of the section (see above)
       cover - thickness of the cover patches
       coreID - material tag for the core patch
       coverID - material tag for the cover patches
       steelID - material tag for the reinforcing steel
       numBars - number of reinforcing bars on any given side of the section
       barArea - cross-sectional area of each reinforcing bar
       nfCoreY - number of fibers in the core patch in the y direction
       nfCoreZ - number of fibers in the core patch in the z direction
       nfCoverY - number of fibers in the cover patches with long sides in the y direction
       nfCoverZ - number of fibers in the cover patches with long sides in the z direction

    Notes
       The thickness of cover concrete is constant on all sides of the core.
       The number of bars is the same on any given side of the section.
       The reinforcing bars are all the same size.
       The number of fibers in the short direction of the cover patches is set to 1.

    Written: Andreas Schellenberg (andreas.schellenberg@gmail.com)
    Date: June 2017
    """

    # The distance from the section z-axis to the edge of the cover concrete
    # in the positive y direction
    coverY = h/2.0

    # The distance from the section y-axis to the edge of the cover concrete
    # in the positive z direction
    coverZ = b/2.0

    # Determine the corresponding values from the respective axes to the
    # edge of the core concrete
    coreY = coverY - cover
    coreZ = coverZ - cover

    # Define the fiber section
    model.section("Fiber", id, GJ=GJ)

    # Define the core patch
    model.patch("quad", coreID, nfCoreZ, nfCoreY, -coreY, coreZ, -coreY, -coreZ, coreY, -coreZ, coreY, coreZ)

    # Define the four cover patches
    model.patch("quad", coverID, 1,        nfCoverY, -coverY,  coverZ, -coreY,   coreZ,   coreY,   coreZ,   coverY,  coverZ)
    model.patch("quad", coverID, 1,        nfCoverY, -coreY,  -coreZ,  -coverY, -coverZ,  coverY, -coverZ,  coreY,  -coreZ)
    model.patch("quad", coverID, nfCoverZ, 1,        -coverY,  coverZ, -coverY, -coverZ, -coreY,  -coreZ,  -coreY,   coreZ)
    model.patch("quad", coverID, nfCoverZ, 1,         coreY,   coreZ,   coreY,  -coreZ,   coverY, -coverZ,  coverY,  coverZ)

    # Define the steel along constant values of y (in the z direction)
    model.layer("straight", steelID, numBars, barArea, -coreY, coreZ, -coreY, -coreZ)
    model.layer("straight", steelID, numBars, barArea,  coreY, coreZ,  coreY, -coreZ)

    # Determine the spacing for the remaining bars in the y direction
    spacingY = (2.0*coreY)/(numBars-1)

    # Avoid double counting bars
    numBars = numBars-2

    # Define remaining steel in the y direction
    model.layer("straight", steelID, numBars, barArea, coreY-spacingY,  coreZ, (-coreY+spacingY),  coreZ)
    model.layer("straight", steelID, numBars, barArea, coreY-spacingY, -coreZ, (-coreY+spacingY), -coreZ)


def create_frame_model(elastic: bool):

    # create Model in three-dimensions with 6 DOF/node
    model = xara.Model(ndm=3, ndf=6)

    # Geometry and Material Properties
        # Nodes(location)
        # Boundary conditions(nodes)
        # Elements(nodes, material properties,                             geometric transformation)
                          # non-fiber section elastic (linear)              # linear
                          # fiber section (linear elastic OR inelastic)     # PDelta
                                                                            # corotational

    # Geometry
    # ---------------

    # Set parameters for model geometry
    h  = 82.0;      # Story height 82 144
    by = 96.0;      # Bay width in Y-direction 96 240
    bx = 72.0;      # Bay width in X-direction 72 240

    # Create nodes
    #            tag    X        Y       Z 
    model.node( 1, (-bx/2.0,  by/2.0,   0.0))
    model.node( 2, ( bx/2.0,  by/2.0,   0.0))
    model.node( 3, ( bx/2.0, -by/2.0,   0.0))
    model.node( 4, (-bx/2.0, -by/2.0,   0.0))

    model.node( 5, (-bx/2.0,  by/2.0,     h))
    model.node( 6, ( bx/2.0,  by/2.0,     h))
    model.node( 7, ( bx/2.0, -by/2.0,     h))
    model.node( 8, (-bx/2.0, -by/2.0,     h))

    model.node(10, (-bx/2.0,  by/2.0, 2.0*h))
    model.node(11, ( bx/2.0,  by/2.0, 2.0*h))
    model.node(12, ( bx/2.0, -by/2.0, 2.0*h))
    model.node(13, (-bx/2.0, -by/2.0, 2.0*h))

    model.node(15, (-bx/2.0,  by/2.0, 3.0*h))
    model.node(16, ( bx/2.0,  by/2.0, 3.0*h))
    model.node(17, ( bx/2.0, -by/2.0, 3.0*h))
    model.node(18, (-bx/2.0, -by/2.0, 3.0*h))


    # Set base constraints
    #      tag DX DY DZ RX RY RZ
    model.fix(1, (1, 1, 1, 1, 1, 1))
    model.fix(2, (1, 1, 1, 1, 1, 1))
    model.fix(3, (1, 1, 1, 1, 1, 1))
    model.fix(4, (1, 1, 1, 1, 1, 1))


    # Define materials for nonlinear columns
    # --------------------------------------
    # CONCRETE
    fc = 4.0 # unconfined
    fpc = 5.0 # confined
    Ec = 57000.0*math.sqrt(fc*1000.0)/1000.0
    if not elastic:
        # Core concrete (confined)
        #                                 tag  f'c   epsc0  f'cu  epscu
        model.uniaxialMaterial("Concrete01", 1, -fpc, -2*fpc/Ec, -3.5, -0.02)
        # Cover concrete (unconfined)
        #                                 tag  f'c   epsc0  f'cu  epscu
        model.uniaxialMaterial("Concrete01", 2, -fc, -2*fc/Ec, 0.0, -0.006)
    else:
        # Core concrete
        model.uniaxialMaterial("Elastic", 1, Ec)
        # Cover concrete
        model.uniaxialMaterial("Elastic", 2, Ec)

    # STEEL
    fy = 60.0;       # Yield stress
    Es = 30000.0;    # Young's modulus
    # Reinforcing steel 
    if not elastic:
        #                                tag fy  E0  b
        model.uniaxialMaterial("Steel01", 3, fy, Es, 0.02)
    else:
        model.uniaxialMaterial("Elastic", 3, Es)


    # Define column elements
    # ----------------------
    # Column parameters
    h_col  = 20.0
    b_col = 20.0
    GJ = 1.0E10
    colSec = 1
    beamSec = 2

    ReinforcedRectangle(model, colSec,
                        h=h_col, 
                        b=b_col,
                        cover=2.5, 
                        coreID=1,
                        coverID=2,
                        steelID=3,
                        numBars=3,
                        barArea=0.79,
                        nfCoreY=8,      
                        nfCoreZ=8,      
                        nfCoverY=10,      
                        nfCoverZ=10,
                        GJ=GJ)
    # Number of column integration points (sections)
    itg_col = 1
    npts_col = 4
    model.beamIntegration("Lobatto", itg_col, colSec, npts_col)
        
    # Geometric transformation for columns
    colTransf = 1
    model.geomTransf("Linear", colTransf, (1.0, 0.0, 0.0))

    #                                tag ndI ndJ transfTag integrationTag
    model.element("forceBeamColumn",  1, ( 1,  5), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  2, ( 2,  6), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  3, ( 3,  7), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  4, ( 4,  8), transform=colTransf, section=colSec, shear=0)

    model.element("forceBeamColumn",  5, ( 5, 10), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  6, ( 6, 11), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  7, ( 7, 12), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  8, ( 8, 13), transform=colTransf, section=colSec, shear=0)

    model.element("forceBeamColumn",  9, (10, 15), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn", 10, (11, 16), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn", 11, (12, 17), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn", 12, (13, 18), transform=colTransf, section=colSec, shear=0)

    # Define beam elements
    # --------------------

    # Define material properties for elastic beams
    # Using beam depth of 24 and width of 18
    Abeam = 18.0*24.0
    # Second moments of area
    Ibeamzz = 1.0/12.0*18.0*pow(24.0,3)
    Ibeamyy = 1.0/12.0*24.0*pow(18.0,3)
    Jbeam = Ibeamzz + Ibeamyy

    nu = 0.2
    Gb = Ec/(2 * (1 + nu))

    # Define elastic section for beams
    #                       tag     E    A      Iz       Iy     G    J
    model.section("Elastic", beamSec, Ec, Abeam, Ibeamzz, Ibeamyy, Gb, Jbeam)

    # Geometric transformation for beams
    beamTransf = 2
    model.geomTransf("Linear", beamTransf, 0.0, 0.0, 1.0)

    # Create the beam elements
    #                   tag (ndI ndJ) transfTag integrationTag
    model.element("elasticBeamColumn", 13, ( 5,  6), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 14, ( 6,  7), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 15, ( 7,  8), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 16, ( 8,  5), transform=beamTransf, section=beamSec, shear=0)

    model.element("elasticBeamColumn", 17, (10, 11), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 18, (11, 12), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 19, (12, 13), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 20, (13, 10), transform=beamTransf, section=beamSec, shear=0)

    model.element("elasticBeamColumn", 21, (15, 16), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 22, (16, 17), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 23, (17, 18), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 24, (18, 15), transform=beamTransf, section=beamSec, shear=0)

    # Lumped mass at nodes on top of columns
    # 10% of axial column capacity assuming unconfined concrete
    p = 0.1*fc*b_col*h_col
    m = p/units.gravity
    #         tag   MX MY MZ   RX   RY   RZ
    model.mass( 5, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 6, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 7, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 8, (m, m, m, 0.0, 0.0, 0.0))

    model.mass( 10, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 11, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 12, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 13, (m, m, m, 0.0, 0.0, 0.0))

    model.mass( 15, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 16, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 17, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 18, (m, m, m, 0.0, 0.0, 0.0))

    # Define gravity loads
    # create a Plain load pattern with Constant scaling
    model.pattern("Plain", 1, "Constant")

    for i in [5, 6, 7, 8, 10, 11, 12, 13, 15, 16, 17, 18]:
        model.load(i, (0.0, 0.0, -p, 0.0, 0.0, 0.0), pattern=1)

    # set rayleigh damping factors
    model.rayleigh(0.0319, 0.0, 0.0125, 0.0)

    return model


def apply_load_frame_model(model, inputx=None, inputy=None, dt=None):
    """
    Add dynamic loads to frame model
    """
    if np.all(inputx is None) or np.all(inputy is None) or dt is None:
        raise ValueError("Missing inputx, inputy, or dt. Exiting.")
    
    # Define earthquake excitation
    # ----------------------------
    # Set up the acceleration records for fault normal (x, dof 1) and fault parallel (y, dof 2)
    model.timeSeries("Path", 2, values=inputx.tolist(), dt=dt, factor=1.0)
    model.timeSeries("Path", 3, values=inputy.tolist(), dt=dt, factor=1.0)

    # Define the excitation using the given ground motion records
    #                         tag dir         accel series args
    model.pattern("UniformExcitation", 2, 1, accel=2)
    model.pattern("UniformExcitation", 3, 2, accel=3)

    return model


def create_bridge_model111(elastic: bool = True, girder: str = "elasticBeamColumn"):
    
    # #input check
    # if np.all(inputx is None) or np.all(inputy is None) or dt is None:
    #     raise ValueError("Missing inputx, inputy, or dt. Exiting.")

    # if girder != "elasticBeamColumn":
    #     raise ValueError("Only elasticBeamColumn allowed for girders.")
    
    model = xara.Model(ndm=3, ndf=6)

    if not hasattr(model, "meta") or not isinstance(model.meta, dict):
        model.meta = {}
    model.meta["column_elems"] = []

    # # Nodes: (tag, (x, y, z))
    # model.node(0, (0.0,                                  0.0,                  320.0)) # abutment 1
    # model.node(1, (3180.0,                               0.0,                  320.0)) # abutment 2
    # model.node(2, (1752.0,                               0.0,                  320.0)) # mid-deck
    # model.node(3, (1641.4628263430573,    199.41297159396336,                  320.0)) # top of column 1
    # model.node(4, (1641.4628263430573,    199.41297159396336,                    0.0)) # bottom of column 1
    # model.node(5, (1862.5371736569432,   -199.41297159396336,                  320.0)) # top of column 2
    # model.node(6, (1862.5371736569432,   -199.41297159396336,                    0.0)) # bottom of column 2

    # model.node(7, (1641.4628263430573, 0.0, 320.0))  # centerline node under col top 3
    # model.node(8, (1862.5371736569432, 0.0, 320.0))  # centerline node under col top 5

    # model.node(9, (54, 0.0, 320.0))  
    # model.node(10, (3102, 0.0, 320.0))

    y_off = 199.41297159396336

    # keep original centerline abutment nodes if you want, but DO NOT connect deck to them
    model.node(0, (0.0,    0.0, 320.0))
    model.node(1, (3180.0, 0.0, 320.0))

    # mid-deck centerline node (optional output only, not connected in scheme A unless you add it)
    # model.node(2, (1752.0, 0.0, 320.0))

    # column top/bottom
    model.node(3, (1641.4628263430573,  y_off, 320.0))  # top col 1 (+y)
    model.node(4, (1641.4628263430573,  y_off,   0.0))  # bot col 1
    model.node(5, (1862.5371736569432, -y_off, 320.0))  # top col 2 (-y)
    model.node(6, (1862.5371736569432, -y_off,   0.0))  # bot col 2

    # girder abutment nodes on two lines (scheme A)
    model.node(11, (0.0,    y_off, 320.0))   # left, +y girder
    model.node(12, (0.0,   -y_off, 320.0))   # left, -y girder
    model.node(13, (3180.0, y_off, 320.0))   # right, +y girder
    model.node(14, (3180.0,-y_off, 320.0))   # right, -y girder  

    # Boundary conditions, fully fixed at 0, 1, 4, 6
    # fix(tag, (DX, DY, DZ, RX, RY, RZ))
    model.fix(0, (1, 1, 1, 1, 1, 1))
    model.fix(1, (1, 1, 1, 1, 1, 1))
    model.fix(4, (1, 0, 1, 1, 1, 1))
    model.fix(6, (1, 0, 1, 1, 1, 1))

    # model.fix(11, (1, 1, 1, 1, 1, 1))
    # model.fix(12, (1, 1, 1, 1, 1, 1))
    # model.fix(13, (1, 1, 1, 1, 1, 1))
    # model.fix(14, (1, 1, 1, 1, 1, 1))

    model.fix(11, (1, 1, 1, 0, 0, 0))
    model.fix(12, (0, 1, 1, 0, 0, 0))
    model.fix(13, (0, 1, 1, 0, 0, 0))
    model.fix(14, (0, 0, 1, 0, 0, 0))

    # Materials: concrete and steel

    # Concrete strengths (ksi)
    fc_unconf = 4.0   # unconfined concrete
    fc_conf   = 5.0  # confined concrete

    # Concrete modulus (ksi), same formula as your frame model
    Ec = 57000.0 * math.sqrt(fc_unconf * 1000.0) / 1000.0

    # Steel properties
    fy = 60.0   # ksi
    Es = 30000.0

    if not elastic:
        # Nonlinear concrete (core and cover) using Concrete01
        #                    tag  f'c       epsc0         f'cu   epscu
        model.uniaxialMaterial("Concrete01", 1, -fc_conf,   -2*fc_conf/Ec,  -3.5,  -0.02)
        model.uniaxialMaterial("Concrete01", 2, -fc_unconf, -2*fc_unconf/Ec, 0.0,  -0.006)

        # Nonlinear reinforcing steel
        #                    tag fy   E0   b
        model.uniaxialMaterial("Steel01", 3, fy, Es, 0.02)
    else:
        # Elastic concrete for both core and cover
        model.uniaxialMaterial("Elastic", 1, Ec)
        model.uniaxialMaterial("Elastic", 2, Ec)

        # Elastic steel
        model.uniaxialMaterial("Elastic", 3, Es)

    
    # Section properties: 5 ft circular section
    # Geometry of circular section
    D_total = 60 #60.0        # total diameter in inches (5 ft)
    cover   = 2.0         # concrete cover in inches
    R_ext   = D_total / 2.0
    R_core  = R_ext - cover  # approximate core radius

    # mesh subdivisions for nonlinear fiber section
    numSubdivCirc = 32
    numSubdivRad  = 5
    divs = (numSubdivCirc, numSubdivRad)

    # tags
    
    colSec_fiber   = 1
    beamSec_elastic = 2   # beams stay elastic

    # ELASTIC SECTION (for elasticBeamColumn model)
    A_el = math.pi * R_ext**2
    I_el = math.pi * R_ext**4 / 4.0
    J_el = math.pi * R_ext**4 / 2.0
    nu = 0.2
    Gc = Ec / (2*(1+nu))
    GJ   = Gc * J_el
    
    model.section("Fiber", colSec_fiber, "-GJ", GJ)
    itg_col = 1
    npts_col = 4
    model.beamIntegration("Lobatto", itg_col, colSec_fiber, npts_col)

    numSubdivCirc, numSubdivRad = divs

    # core concrete
    model.patch("circ",
                1,                      # matTag = 1
                numSubdivCirc, numSubdivRad,
                0.0, 0.0,               # yCenter, zCenter
                0.0, R_core,            # intRad, extRad
                0.0, 2 * math.pi)

    # cover concrete
    model.patch("circ",
                2,                      # matTag = 2
                numSubdivCirc, numSubdivRad,
                0.0, 0.0,
                R_core, R_ext,
                0.0, 2 * math.pi)

    # longitudinal steel
    numBars = 36 # 36
    barArea = 1.56 #1.56                    # #11 bar area
    model.layer("circ",
                3,                    # steel matTag
                numBars, barArea,
                0.0, 0.0,            # yCenter, zCenter
                R_core,              # radius
                0.0, 2 * math.pi)
   

    beam_stiff_factor = 5.0
    A_beam = 864.0          # 24in × 36in = 864 in^2
    I_beam = 9.33e4 * beam_stiff_factor        # in^4  (strong axis)
    J_beam = 3.73e5 * beam_stiff_factor        # in^4  approximate torsion

    model.section("Elastic", beamSec_elastic, Ec, A_beam, I_beam, I_beam, Gc, J_beam)

    

    # Transformations and elements
    colTransf  = 1
    beamTransf = 2
    model.geomTransf("Linear", colTransf,  (1.0, 0.0, 0.0))
    model.geomTransf("Linear", beamTransf, 0.0, 0.0, 1.0)

    # columns: elastic vs nonlinear
    
    # columns as elasticBeamColumn with elastic section
    col_type = "forceBeamColumn"
    sec_col  = colSec_fiber

    model.element(col_type, 2, (4, 3), transform=colTransf, section=sec_col, shear=0)
    model.element(col_type, 3, (6, 5), transform=colTransf, section=sec_col, shear=0)
    

    model.meta["column_elems"] = [2, 3]

    # beams always elastic
    beam_type = "elasticBeamColumn"
    sec_beam  = beamSec_elastic

    # replace your deck elements (0-2 and 2-1) with these
    # model.element(beam_type, 101, (0, 9), transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 102, (9, 7),  transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 103, (7, 2),  transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 104, (2, 8),  transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 105, (8, 10), transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 106, (10, 1), transform=beamTransf, section=sec_beam, shear=0)

    # model.element(beam_type, 1, (0, 2), transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 4, (2, 1), transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 5, (3, 2), transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 6, (5, 2), transform=beamTransf, section=sec_beam, shear=0)

    # model.rigidLink("beam", 7, 3)  # master=7 (centerline), slave=3 (col top)
    # model.rigidLink("beam", 8, 5)

    # +y girder: 11 -- 3 -- 13
    model.element(beam_type, 201, (11, 3), transform=beamTransf, section=sec_beam, shear=0)
    model.element(beam_type, 202, (3, 13), transform=beamTransf, section=sec_beam, shear=0)

    # -y girder: 12 -- 5 -- 14
    model.element(beam_type, 203, (12, 5), transform=beamTransf, section=sec_beam, shear=0)
    model.element(beam_type, 204, (5, 14), transform=beamTransf, section=sec_beam, shear=0)

    # diaphragms / cross-beams tying the two girders together
    model.element(beam_type, 301, (11, 12), transform=beamTransf, section=sec_beam, shear=0)
    model.element(beam_type, 302, (3,  5),  transform=beamTransf, section=sec_beam, shear=0)
    model.element(beam_type, 303, (13, 14), transform=beamTransf, section=sec_beam, shear=0)


    # Mass, damping and earthquake excitation
    # lump_mass = 1.0  # placeholder
    # for nd in [2, 3, 5]:
    #     # mass(tag, (MX, MY, MZ, RX, RY, RZ))
    #     model.mass(nd, (lump_mass, lump_mass, 0.0, 0.0, 0.0, 0.0))

    # ---------- Gravity load and mass: template style ----------
    output_nodes = [3,5]
    print('pre-gravity disp')
    for node in output_nodes:
        print(node, model.nodeDisp(node))
    
    
    A_col     = math.pi * (D_total/2.0)**2 

    #  fc * A
    P_col_cap = fc_conf * A_col   #  kips

    # 10% 
    P_grav_total = 0.05 * P_col_cap         # kips
    P_per_col    = P_grav_total / 2.0      # kips

    # 
    g = units.gravity   # in/s^2
    m_per_node = P_per_col / g             # kip / (in/s^2) 

    # 
    for nd in [3, 5]:
        # mass(MX, MY, MZ, RX, RY, RZ)
        model.mass(nd, (m_per_node/90, m_per_node/90, m_per_node/10, 0.0, 0.0, 0.0)) #909010

    # Plain + Constant
    model.pattern("Plain", 1, "Constant")
    # for nd in [2, 3, 5]:
    #     model.load(nd, (0.0, 0.0, -P_per_col/2.0, 0.0, 0.0, 0.0), pattern=1)

    for nd in [3, 5]:
        model.load(nd, (0,0,-P_grav_total,0,0,0), pattern=1)


    print("post-gravity")
    for n in output_nodes:
        print(n, model.nodeDisp(n))

    # rayleigh(alphaM, betaK, betaKinit, betaKcomm)
    model.rayleigh(0.0319, 0.0, 0.0125, 0.0)

    # # Ground motion: fault normal (x) and fault parallel (y) components
    # # Time series for the two components
    # model.timeSeries("Path", 2, values=inputx.tolist(), dt=dt, factor=1.0)
    # model.timeSeries("Path", 3, values=inputy.tolist(), dt=dt, factor=1.0)

    # # Uniform excitation patterns in global X and Y directions
    # # pattern("UniformExcitation", tag, dof, accel=seriesTag)
    # model.pattern("UniformExcitation", 2, 1, accel=2)   # dof 1 = global X
    # model.pattern("UniformExcitation", 3, 2, accel=3)   # dof 2 = global Y

    return model

def create_bridge_model(elastic: bool = True, girder: str = "elasticBeamColumn"):
    
    # #input check
    # if np.all(inputx is None) or np.all(inputy is None) or dt is None:
    #     raise ValueError("Missing inputx, inputy, or dt. Exiting.")

    # if girder != "elasticBeamColumn":
    #     raise ValueError("Only elasticBeamColumn allowed for girders.")
    
    model = xara.Model(ndm=3, ndf=6)

    if not hasattr(model, "meta") or not isinstance(model.meta, dict):
        model.meta = {}
    model.meta["column_elems"] = []

    # # Nodes: (tag, (x, y, z))
    # model.node(0, (0.0,                                  0.0,                  320.0)) # abutment 1
    # model.node(1, (3180.0,                               0.0,                  320.0)) # abutment 2
    # model.node(2, (1752.0,                               0.0,                  320.0)) # mid-deck
    # model.node(3, (1641.4628263430573,    199.41297159396336,                  320.0)) # top of column 1
    # model.node(4, (1641.4628263430573,    199.41297159396336,                    0.0)) # bottom of column 1
    # model.node(5, (1862.5371736569432,   -199.41297159396336,                  320.0)) # top of column 2
    # model.node(6, (1862.5371736569432,   -199.41297159396336,                    0.0)) # bottom of column 2
    # model.node(9, (54, 0.0, 320.0))  
    # model.node(10, (3102, 0.0, 320.0))  

    model.node(0, (0.0,                                  0.0,                  320.0)) # abutment 1
    model.node(1, (3180.0,                               0.0,                  320.0)) # abutment 2
    model.node(2, (1590.0,                               0.0,                  320.0)) # mid-deck
    model.node(3, (1590,    199.41297159396336,                  320.0)) # top of column 1
    model.node(4, (1590,    199.41297159396336,                    0.0)) # bottom of column 1
    model.node(5, (1590,   -199.41297159396336,                  320.0)) # top of column 2
    model.node(6, (1590,   -199.41297159396336,                    0.0)) # bottom of column 2
    model.node(9, (54, 0.0, 320.0))  
    model.node(10, (3126, 0.0, 320.0))  

    # Boundary conditions, fully fixed at 0, 1, 4, 6
    # fix(tag, (DX, DY, DZ, RX, RY, RZ))
    # model.fix(0, (0, 0, 1, 1, 1, 1))
    # model.fix(1, (0, 0, 1, 1, 1, 1))
    # model.fix(4, (0, 0, 1, 1, 1, 1))
    # model.fix(6, (0, 0, 1, 1, 1, 1))

    # model.fix(0, (1, 1, 1, 1, 1, 1))
    # model.fix(1, (1, 1, 1, 1, 1, 1))
    # model.fix(4, (1, 0, 1, 1, 1, 1))
    # model.fix(6, (1, 0, 1, 1, 1, 1))

    model.fix(0, (1, 1, 1, 1, 1, 1))
    model.fix(1, (0, 1, 1, 1, 1, 1))
    model.fix(4, (1, 1, 1, 1, 1, 1))
    model.fix(6, (1, 1, 1, 1, 1, 1))

    # Materials: concrete and steel

    # Concrete strengths (ksi)
    fc_unconf = 4.0   # unconfined concrete
    fc_conf   = 5.0  # confined concrete

    # Concrete modulus (ksi), same formula as your frame model
    Ec = 57000.0 * math.sqrt(fc_unconf * 1000.0) / 1000.0

    # Steel properties
    fy = 60.0   # ksi
    Es = 30000.0

    if not elastic:
        # Nonlinear concrete (core and cover) using Concrete01
        #                    tag  f'c       epsc0         f'cu   epscu
        model.uniaxialMaterial("Concrete01", 1, -fc_conf,   -2*fc_conf/Ec,  -3.5,  -0.02)
        model.uniaxialMaterial("Concrete01", 2, -fc_unconf, -2*fc_unconf/Ec, 0.0,  -0.006)

        # Nonlinear reinforcing steel
        #                    tag fy   E0   b
        model.uniaxialMaterial("Steel01", 3, fy, Es, 0.02)
    else:
        # Elastic concrete for both core and cover
        model.uniaxialMaterial("Elastic", 1, Ec)
        model.uniaxialMaterial("Elastic", 2, Ec)

        # Elastic steel
        model.uniaxialMaterial("Elastic", 3, Es)

    
    # Section properties: 5 ft circular section
    # Geometry of circular section
    D_total = 30 #60.0        # total diameter in inches (5 ft)
    cover   = 2.0         # concrete cover in inches
    R_ext   = D_total / 2.0
    R_core  = R_ext - cover  # approximate core radius

    # mesh subdivisions for nonlinear fiber section
    numSubdivCirc = 32
    numSubdivRad  = 5
    divs = (numSubdivCirc, numSubdivRad)

    # tags
    
    colSec_fiber   = 1
    beamSec_elastic = 2   # beams stay elastic

    # ELASTIC SECTION (for elasticBeamColumn model)
    A_el = math.pi * R_ext**2
    I_el = math.pi * R_ext**4 / 4.0
    J_el = math.pi * R_ext**4 / 2.0
    nu = 0.2
    Gc = Ec / (2*(1+nu))
    GJ   = Gc * J_el
    
    model.section("Fiber", colSec_fiber, "-GJ", GJ)
    itg_col = 1
    npts_col = 4
    model.beamIntegration("Lobatto", itg_col, colSec_fiber, npts_col)

    numSubdivCirc, numSubdivRad = divs

    # core concrete
    model.patch("circ",
                1,                      # matTag = 1
                numSubdivCirc, numSubdivRad,
                0.0, 0.0,               # yCenter, zCenter
                0.0, R_core,            # intRad, extRad
                0.0, 2 * math.pi)

    # cover concrete
    model.patch("circ",
                2,                      # matTag = 2
                numSubdivCirc, numSubdivRad,
                0.0, 0.0,
                R_core, R_ext,
                0.0, 2 * math.pi)

    # longitudinal steel
    numBars = 18 # 36
    barArea = 1.56 #1.56                    # #11 bar area
    model.layer("circ",
                3,                    # steel matTag
                numBars, barArea,
                0.0, 0.0,            # yCenter, zCenter
                R_core,              # radius
                0.0, 2 * math.pi)
   

    beam_stiff_factor = 5.0
    A_beam = 864.0          # 24in × 36in = 864 in^2
    I_beam = 9.33e4 * beam_stiff_factor        # in^4  (strong axis)
    J_beam = 3.73e5 * beam_stiff_factor        # in^4  approximate torsion

    model.section("Elastic", beamSec_elastic, Ec, A_beam, I_beam, I_beam, Gc, J_beam)

    

    # Transformations and elements
    colTransf  = 1
    beamTransf = 2
    model.geomTransf("Linear", colTransf,  (1.0, 0.0, 0.0))
    model.geomTransf("Linear", beamTransf, 0.0, 0.0, 1.0)

    # columns: elastic vs nonlinear
    
    # columns as elasticBeamColumn with elastic section
    col_type = "forceBeamColumn"
    sec_col  = colSec_fiber

    model.element(col_type, 2, (4, 3), transform=colTransf, section=sec_col, shear=0)
    model.element(col_type, 3, (6, 5), transform=colTransf, section=sec_col, shear=0)
    

    model.meta["column_elems"] = [2, 3]

    # beams always elastic
    beam_type = "elasticBeamColumn"
    sec_beam  = beamSec_elastic

    
    model.element(beam_type, 101, (0, 9), transform=beamTransf, section=sec_beam, shear=0)
    
    model.element(beam_type, 102, (9, 2),  transform=beamTransf, section=sec_beam, shear=0)
    
    model.element(beam_type, 103, (2, 10), transform=beamTransf, section=sec_beam, shear=0)
    model.element(beam_type, 104, (10, 1), transform=beamTransf, section=sec_beam, shear=0)

    model.element(beam_type, 105, (3, 2), transform=beamTransf, section=sec_beam, shear=0)
    model.element(beam_type, 106, (5, 2), transform=beamTransf, section=sec_beam, shear=0)

    # model.element(beam_type, 1, (0, 2), transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 4, (2, 1), transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 5, (3, 2), transform=beamTransf, section=sec_beam, shear=0)
    # model.element(beam_type, 6, (5, 2), transform=beamTransf, section=sec_beam, shear=0)

    # Mass, damping and earthquake excitation
    # lump_mass = 1.0  # placeholder
    # for nd in [2, 3, 5]:
    #     # mass(tag, (MX, MY, MZ, RX, RY, RZ))
    #     model.mass(nd, (lump_mass, lump_mass, 0.0, 0.0, 0.0, 0.0))

    # ---------- Gravity load and mass: template style ----------
    output_nodes = [2,3,5]
    print('pre-gravity disp')
    for node in output_nodes:
        print(node, model.nodeDisp(node))
    
    
    A_col     = math.pi * (D_total/2.0)**2 

    #  fc * A
    P_col_cap = fc_conf * A_col   #  kips

    # 10% 
    P_grav_total = 0.05 * P_col_cap         # kips
    P_per_col    = P_grav_total / 2.0      # kips

    # 
    g = units.gravity   # in/s^2
    m_per_node = P_per_col / g             # kip / (in/s^2) 

    # 
    for nd in [2, 9, 10]:
        # mass(MX, MY, MZ, RX, RY, RZ)
        model.mass(nd, (m_per_node/90, m_per_node/90, m_per_node/10, 0.0, 0.0, 0.0)) #909010

    # Plain + Constant
    model.pattern("Plain", 1, "Constant")
    # for nd in [2, 3, 5]:
    #     model.load(nd, (0.0, 0.0, -P_per_col/2.0, 0.0, 0.0, 0.0), pattern=1)

    for nd in [2, 9, 10]:
        model.load(nd, (0,0,-P_grav_total,0,0,0), pattern=1)


    print("post-gravity")
    for n in output_nodes:
        print(n, model.nodeDisp(n))

    # rayleigh(alphaM, betaK, betaKinit, betaKcomm)
    model.rayleigh(0.0319, 0.0, 0.0125, 0.0)

    # # Ground motion: fault normal (x) and fault parallel (y) components
    # # Time series for the two components
    # model.timeSeries("Path", 2, values=inputx.tolist(), dt=dt, factor=1.0)
    # model.timeSeries("Path", 3, values=inputy.tolist(), dt=dt, factor=1.0)

    # # Uniform excitation patterns in global X and Y directions
    # # pattern("UniformExcitation", tag, dof, accel=seriesTag)
    # model.pattern("UniformExcitation", 2, 1, accel=2)   # dof 1 = global X
    # model.pattern("UniformExcitation", 3, 2, accel=3)   # dof 2 = global Y

    return model

def create_bridge_model1(elastic: bool = True, girder: str = "elasticBeamColumn"):
    
    # #input check
    # if np.all(inputx is None) or np.all(inputy is None) or dt is None:
    #     raise ValueError("Missing inputx, inputy, or dt. Exiting.")

    # if girder != "elasticBeamColumn":
    #     raise ValueError("Only elasticBeamColumn allowed for girders.")
    
    model = xara.Model(ndm=3, ndf=6)

    if not hasattr(model, "meta") or not isinstance(model.meta, dict):
        model.meta = {}
    model.meta["column_elems"] = []

    # Nodes: (tag, (x, y, z))
    model.node(0, (0.0,                                  0.0,                  320.0)) # abutment 1
    model.node(1, (3180.0,                               0.0,                  320.0)) # abutment 2
    model.node(2, (1752.0,                               0.0,                  320.0)) # mid-deck
    model.node(3, (1641.4628263430573,    199.41297159396336,                  320.0)) # top of column 1
    model.node(4, (1641.4628263430573,    199.41297159396336,                    0.0)) # bottom of column 1
    model.node(5, (1862.5371736569432,   -199.41297159396336,                  320.0)) # top of column 2
    model.node(6, (1862.5371736569432,   -199.41297159396336,                    0.0)) # bottom of column 2

    # Boundary conditions, fully fixed at 0, 1, 4, 6
    # fix(tag, (DX, DY, DZ, RX, RY, RZ))
    model.fix(0, (1, 1, 1, 1, 1, 1))
    model.fix(1, (1, 1, 1, 1, 1, 1))
    model.fix(4, (1, 0, 1, 1, 1, 1))
    model.fix(6, (1, 0, 1, 1, 1, 1))

    # Materials: concrete and steel

    # Concrete strengths (ksi)
    fc_unconf = 4.0   # unconfined concrete
    fc_conf   = 5.0  # confined concrete

    # Concrete modulus (ksi), same formula as your frame model
    Ec = 57000.0 * math.sqrt(fc_unconf * 1000.0) / 1000.0

    # Steel properties
    fy = 60.0   # ksi
    Es = 30000.0

    if not elastic:
        # Nonlinear concrete (core and cover) using Concrete01
        #                    tag  f'c       epsc0         f'cu   epscu
        model.uniaxialMaterial("Concrete01", 1, -fc_conf,   -2*fc_conf/Ec,  -3.5,  -0.02)
        model.uniaxialMaterial("Concrete01", 2, -fc_unconf, -2*fc_unconf/Ec, 0.0,  -0.006)

        # Nonlinear reinforcing steel
        #                    tag fy   E0   b
        model.uniaxialMaterial("Steel01", 3, fy, Es, 0.02)
    else:
        # Elastic concrete for both core and cover
        model.uniaxialMaterial("Elastic", 1, Ec)
        model.uniaxialMaterial("Elastic", 2, Ec)

        # Elastic steel
        model.uniaxialMaterial("Elastic", 3, Es)

    
    # Section properties: 5 ft circular section
    # Geometry of circular section
    D_total = 60 #60.0        # total diameter in inches (5 ft)
    cover   = 2.0         # concrete cover in inches
    R_ext   = D_total / 2.0
    R_core  = R_ext - cover  # approximate core radius

    # mesh subdivisions for nonlinear fiber section
    numSubdivCirc = 32
    numSubdivRad  = 5
    divs = (numSubdivCirc, numSubdivRad)

    # tags
    
    colSec_fiber   = 1
    beamSec_elastic = 2   # beams stay elastic

    # ELASTIC SECTION (for elasticBeamColumn model)
    A_el = math.pi * R_ext**2
    I_el = math.pi * R_ext**4 / 4.0
    J_el = math.pi * R_ext**4 / 2.0
    nu = 0.2
    Gc = Ec / (2*(1+nu))
    GJ   = Gc * J_el
    
    model.section("Fiber", colSec_fiber, "-GJ", GJ)
    itg_col = 1
    npts_col = 4
    model.beamIntegration("Lobatto", itg_col, colSec_fiber, npts_col)

    numSubdivCirc, numSubdivRad = divs

    # core concrete
    model.patch("circ",
                1,                      # matTag = 1
                numSubdivCirc, numSubdivRad,
                0.0, 0.0,               # yCenter, zCenter
                0.0, R_core,            # intRad, extRad
                0.0, 2 * math.pi)

    # cover concrete
    model.patch("circ",
                2,                      # matTag = 2
                numSubdivCirc, numSubdivRad,
                0.0, 0.0,
                R_core, R_ext,
                0.0, 2 * math.pi)

    # longitudinal steel
    numBars = 36 # 36
    barArea = 1.56 #1.56                    # #11 bar area
    model.layer("circ",
                3,                    # steel matTag
                numBars, barArea,
                0.0, 0.0,            # yCenter, zCenter
                R_core,              # radius
                0.0, 2 * math.pi)
   

    beam_stiff_factor = 5.0
    A_beam = 864.0          # 24in × 36in = 864 in^2
    I_beam = 9.33e4 * beam_stiff_factor        # in^4  (strong axis)
    J_beam = 3.73e5 * beam_stiff_factor        # in^4  approximate torsion

    model.section("Elastic", beamSec_elastic, Ec, A_beam, I_beam, I_beam, Gc, J_beam)

    

    # Transformations and elements
    colTransf  = 1
    beamTransf = 2
    model.geomTransf("Linear", colTransf,  (1.0, 0.0, 0.0))
    model.geomTransf("Linear", beamTransf, 0.0, 0.0, 1.0)

    # columns: elastic vs nonlinear
    
    # columns as elasticBeamColumn with elastic section
    col_type = "forceBeamColumn"
    sec_col  = colSec_fiber

    model.element(col_type, 2, (4, 3), transform=colTransf, section=sec_col, shear=0)
    model.element(col_type, 3, (6, 5), transform=colTransf, section=sec_col, shear=0)
    

    model.meta["column_elems"] = [2, 3]

    # beams always elastic
    beam_type = "elasticBeamColumn"
    sec_beam  = beamSec_elastic

    model.element(beam_type, 1, (0, 2), transform=beamTransf, section=sec_beam, shear=0)
    model.element(beam_type, 4, (2, 1), transform=beamTransf, section=sec_beam, shear=0)
    model.element(beam_type, 5, (3, 2), transform=beamTransf, section=sec_beam, shear=0)
    model.element(beam_type, 6, (5, 2), transform=beamTransf, section=sec_beam, shear=0)

    # Mass, damping and earthquake excitation
    # lump_mass = 1.0  # placeholder
    # for nd in [2, 3, 5]:
    #     # mass(tag, (MX, MY, MZ, RX, RY, RZ))
    #     model.mass(nd, (lump_mass, lump_mass, 0.0, 0.0, 0.0, 0.0))

    # ---------- Gravity load and mass: template style ----------
    output_nodes = [2,3,5]
    print('pre-gravity disp')
    for node in output_nodes:
        print(node, model.nodeDisp(node))
    
    
    A_col     = math.pi * (D_total/2.0)**2 

    #  fc * A
    P_col_cap = fc_conf * A_col   #  kips

    # 10% 
    P_grav_total = 0.05 * P_col_cap         # kips
    P_per_col    = P_grav_total / 2.0      # kips

    # 
    g = units.gravity   # in/s^2
    m_per_node = P_per_col / g             # kip / (in/s^2) 

    # 
    for nd in [2, 3, 5]:
        # mass(MX, MY, MZ, RX, RY, RZ)
        model.mass(nd, (m_per_node/90, m_per_node/90, m_per_node/10, 0.0, 0.0, 0.0)) #909010

    # Plain + Constant
    model.pattern("Plain", 1, "Constant")
    for nd in [2, 3, 5]:
        model.load(nd, (0.0, 0.0, -P_per_col/2.0, 0.0, 0.0, 0.0), pattern=1)

    print("post-gravity")
    for n in output_nodes:
        print(n, model.nodeDisp(n))

    # rayleigh(alphaM, betaK, betaKinit, betaKcomm)
    model.rayleigh(0.0319, 0.0, 0.0125, 0.0)

    # # Ground motion: fault normal (x) and fault parallel (y) components
    # # Time series for the two components
    # model.timeSeries("Path", 2, values=inputx.tolist(), dt=dt, factor=1.0)
    # model.timeSeries("Path", 3, values=inputy.tolist(), dt=dt, factor=1.0)

    # # Uniform excitation patterns in global X and Y directions
    # # pattern("UniformExcitation", tag, dof, accel=seriesTag)
    # model.pattern("UniformExcitation", 2, 1, accel=2)   # dof 1 = global X
    # model.pattern("UniformExcitation", 3, 2, accel=3)   # dof 2 = global Y

    return model

def apply_load_bridge_model(model, inputx=None, inputy=None, dt=None):
    """
    Add dynamic loads to bridge model
    """
    if np.all(inputx is None) or np.all(inputy is None) or dt is None:
        raise ValueError("Missing inputx, inputy, or dt. Exiting.")
    
    # Define earthquake excitation
    # ----------------------------
    # Set up the acceleration records for fault normal (x, dof 1) and fault parallel (y, dof 2)
    model.timeSeries("Path", 2, values=inputx.tolist(), dt=dt, factor=1.0)
    model.timeSeries("Path", 3, values=inputy.tolist(), dt=dt, factor=1.0)

    # Define the excitation using the given ground motion records
    #                         tag dir         accel series args
    model.pattern("UniformExcitation", 2, 1, accel=2)
    model.pattern("UniformExcitation", 3, 2, accel=3)

    return model


def get_inputs(i, events, input_channels, scale=1):
    event = events[i]
    inputs, dt = extract_channels(event, input_channels)
    inputs = scale*inputs
    return inputs, dt


def save_event_io(i, inputs, outputs, dt, out_dir="event_data"):
    os.makedirs(out_dir, exist_ok=True)
    nt = inputs.shape[1]
    time = np.arange(nt) * dt
    
    csv_in = os.path.join(out_dir, f"event_{i+1}_inputs.csv")
    with open(csv_in, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["time","acc_X","acc_Y"])
        for t, x, y in zip(time, inputs[0], inputs[1]):
            writer.writerow([t, x, y])
    
    csv_out = os.path.join(out_dir, f"event_{i+1}_outputs.csv")
    with open(csv_out, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["time","1F_X","1F_Y","2F_X","2F_Y","3F_X","3F_Y"])
        for idx in range(nt):
            row = [time[idx]] + [outputs[r,idx] for r in range(6)]
            writer.writerow(row)


def get_material_response(model, element, sec_tag, y, z):
    try:
        strain =  model.eleResponse(element, "section", sec_tag, "fiber", y, z, "strain")
        stress =  model.eleResponse(element, "section", sec_tag, "fiber", y, z, "stress")
        return strain, stress
    except Exception as e:
        print(e)
        return None


def apply_gravity_static(
    model,
    output_nodes,
    fixed_nodes=None,
    tol=1e-8,
    max_iter=50,
    n_steps=10,
):
    """
    Solve gravity equilibrium (static), then fix gravity loads as constant.
    Returns model (in-place).
    """

    if fixed_nodes is None:
        fixed_nodes = []  # [0,1,4,6] for bridge, [1,2,3,4] for frame

    print("pre-gravity disp")
    for n in output_nodes:
        print(n, model.nodeDisp(n))

    # fresh analysis objects
    model.wipeAnalysis()

    # static analysis setup
    model.system("BandGen")
    model.numberer("RCM")
    model.constraints("Transformation")
    model.test("NormDispIncr", tol, max_iter)
    model.algorithm("Newton")
    model.integrator("LoadControl", 1.0 / n_steps)
    model.analysis("Static")

    # apply gravity gradually
    for k in range(n_steps):
        ok = model.analyze(1)
        if ok != 0:
            raise RuntimeError(f"gravity static failed at step {k+1}/{n_steps}")

    # check reactions (more reliable than disp)
    if fixed_nodes:
        try:
            model.reactions()
            print("gravity reactions at fixed nodes")
            for nd in fixed_nodes:
                print(nd, model.nodeReaction(nd))
        except Exception as e:
            print("reaction check failed:", e)

    print("post-gravity disp")
    for n in output_nodes:
        print(n, model.nodeDisp(n))

    #check
    check_nodes = [0,1,2,3,4,5,6,9,10]
    print("\n[gravity check] nodeDisp for key nodes")
    for n in check_nodes:
        print(n, model.nodeDisp(n))
    print("\n[gravity check] du = top - base")
    for top, base in [(3,4),(5,6)]:
        uT = model.nodeDisp(top)
        uB = model.nodeDisp(base)
        du = [uT[i]-uB[i] for i in range(6)]
        print(f"{top}-{base} du_XY=({du[0]:+.6e}, {du[1]:+.6e}), du_Z={du[2]:+.6e}, du_R=({du[3]:+.6e},{du[4]:+.6e},{du[5]:+.6e})")
    

    # fix gravity loads as constant and reset time
    model.loadConst("-time", 0.0)

    # wipe analysis again so transient can be configured cleanly
    model.wipeAnalysis()

    return model

def analyze(model, nt, dt, 
            output_nodes=[5,10,15],
            output_elements=[1,5,9],
            n_modes=3,
            yFiber=9.0,
            zFiber=0.0,
            ):

    # ----------------------------
    # 1. Configure the analysis
    # ----------------------------

    # create the system of equation
    model.system("BandGen")

    # create the DOF numberer
    model.numberer("RCM")

    # create the constraint handler
    model.constraints("Transformation")

    # Configure the analysis such that iterations are performed until either:
    # 1. the energy increment is less than 1.0e-14 (success)
    # 2. the number of iterations surpasses 20 (failure)
    #model.test("EnergyIncr", 1.0e-14, 40)
    model.test("NormDispIncr", 1.0e-6, 40)

    # Perform iterations with the Newton-Raphson algorithm
    #model.algorithm("Newton")
    model.algorithm("NewtonLineSearch")

    # define the integration scheme, the Newmark with gamma=0.5 and beta=0.25
    model.integrator("Newmark", 0.5, 0.25)

    # Define the analysis
    model.analysis("Transient")

    # -----------------------
    # 3. Perform the analysis
    # -----------------------

    print("[analyze] pre-dynamic disp ")
    for n in output_nodes:
        print(n, model.nodeDisp(n))
    # record once at time 0
    displacements = {
        node: [model.nodeDisp(node)] for node in output_nodes
    }
    strains = {
        element: [get_material_response(model, element, 1, yFiber, zFiber)[0]] for element in output_elements
    }
    stresses = {
        element: [get_material_response(model, element, 1, yFiber, zFiber)[1]] for element in output_elements
    }

    # get modes
    lambdas = model.eigen(n_modes, "fullGenLapack")  
    omega = np.sqrt(np.abs(lambdas))
    freqs_before = omega/(2*np.pi) 

    # Perform nt analysis steps with a time step of dt
    print(f"Analysis Progress ({nt} timesteps)")
    for i in tqdm.tqdm(range(nt)):
        status = model.analyze(1, dt) 
        if status != 0:
            raise RuntimeError(f"analysis failed at time {model.getTime()}")
        
        # --- add: print right after the first step (t=dt) ---
        if i == 0:
            print(f"[analyze] after 1 step, time={model.getTime():.6f}")
            print("[analyze] disp after first step (check jump)")
            for n in output_nodes:
                print(n, model.nodeDisp(n))

        # Save displacements at the current time
        for node in output_nodes:
            displacements[node].append(model.nodeDisp(node))
        
        for element in output_elements:
            strains[element].append(get_material_response(model, element, 1, yFiber, zFiber)[0])
            stresses[element].append(get_material_response(model, element, 1, yFiber, zFiber)[1])

    lambdas_after = model.eigen(n_modes, "fullGenLapack") 
    omega_after = np.sqrt(np.abs(lambdas_after))   
    freqs_after = omega_after/(2*np.pi)
           
    return displacements, stresses, strains, freqs_before, freqs_after


def write_freq_csv(event_id,
                   freqs_before,
                   freqs_after,
                   freq_csv_path="natural_frequencies.csv"):
    
    n_modes = len(freqs_before)
    
    file_exists = os.path.exists(freq_csv_path)

    with open(freq_csv_path, "a", newline="") as f:
        writer = csv.writer(f)
        if not file_exists:
            header = ["event_id"]
            header += [f"f{i+1}_before_Hz" for i in range(n_modes)] #Hz
            header += [f"f{i+1}_after_Hz" for i in range(n_modes)]
            writer.writerow(header)
        row = [event_id] + list(freqs_before) + list(freqs_after)
        writer.writerow(row)


def get_node_displacements(displacements,
                #nodes=[5,10,15], # building (3 story frame)
                nodes=[2,3,5], # bridge
                dt=None,
                ):
    """
    displacements: { node_id: [ [u1,u2,u3,u4,u5,u6], ... ] }
    Returns outputs: ndarray, shape=(n_nodes*2, nt), row order:
      [Node1 X, Node1 Y, Node2 X, Node2 Y, ...]
    """
    
    rows = []
    for node in nodes:
        arr = np.array(displacements[node])  # shape (nt+1, 6)
        rows.append(arr[:, 0])  # X displacement 
        rows.append(arr[:, 1])  # Y displacement

    outputs = np.vstack(rows)
    return outputs     # shape (2*n_nodes, nt)


def stabilize_with_lmi(A_hat, epsilon=1e-10, solver='CVXOPT'):

    """
    Only the matrix A_s obtained from algorithms such as SRIM is stabilized by imposing a Lyapunov LMI constraint to obtain a stable A. 
    The matrices B_s, C_s, and D_s are directly used as output. 
    This corresponds to Section II of Lacy & Bernstein (2003).
    The solver can be set to either SCS or CVXOPT, and epsilon can be chosen starting from 1e-8.
    """
    n = A_hat.shape[0]

    # #Define only Q and P as variables
    P = cp.Variable((n, n), PSD=True)
    Q = cp.Variable((n, n))

    # —— Objective function ——— (Equation 2.17)
    objective = cp.Minimize(cp.norm(A_hat @ P - Q, "fro")**2)

    # —— Lyapunov LMI constraint ——— (Equation 2.18)
    M = cp.bmat([
        [P - epsilon * np.eye(n), Q],
        [Q.T, P]
    ])
    constraints = [M >> 0]

    # —— Solve the optimization problem —— 
    prob = cp.Problem(objective, constraints)
    prob.solve(solver=solver)

    A_lmi = Q.value @ np.linalg.inv(P.value)
    return A_lmi


def stabilize_by_radius_clipping(A, alpha=0.995, rmin=None, make_real=True):
    w, V = np.linalg.eig(A)             
    r = np.abs(w)
    w_new = w.copy()
    over = r > 1.0
    w_new[over] = alpha * w[over] / r[over]
    if rmin is not None:
        under = np.abs(w_new) < rmin
        w_new[under] = rmin * w_new[under] / (np.abs(w_new[under]) + 1e-15)
    A_new = V @ np.diag(w_new) @ np.linalg.inv(V)
    if make_real and np.allclose(A_new.imag, 0, atol=1e-10):
        A_new = A_new.real
    return A_new


def get_true_modes_xara(model, floor_nodes=(9,14,19), dofs=(1,2), n=3, solver='-genBandArpack'): #-symmBandLapack -genBandArpack
    lambdas = model.eigen(n)  
    print(f"[Debug] eigen(n={n}) returned {len(lambdas)} values: {lambdas}")
    lambdas = np.asarray(lambdas, dtype=float)
    omega = np.sqrt(np.abs(lambdas))                    # rad/s
    freqs_hz = omega / (2*np.pi)
    rows = []
    for node in floor_nodes:
        for dof in dofs:
            rows.append([model.nodeEigenvector(node, k+1, dof) for k in range(n)])
    Phi_true = np.array(rows, dtype=float)              # (6, nmodes)
    Phi_true /= (np.linalg.norm(Phi_true, axis=0, keepdims=True) + 1e-12)
    idx = np.argsort(freqs_hz)         
    freqs_hz = freqs_hz[idx]
    Phi_true = Phi_true[:, idx]       
    return freqs_hz, Phi_true


def mac_matrix(Phi_true, Phi_est):
    print(type(Phi_est))
    print(np.shape(Phi_est))
    T = Phi_true / (np.linalg.norm(Phi_true, axis=0, keepdims=True) + 1e-12)
    E = Phi_est  / (np.linalg.norm(Phi_est,  axis=0, keepdims=True) + 1e-12)
    return np.abs(T.T @ E)**2     


def normalize_v(v):
    """
    Normalize an individual vector:
    element-wise signed complex magnitude, unitized
    i.e.:
    for each element, multiply the sign of its real part
    by the square root of the element multiplied by its
    complex conjugate.
    then, divide the vector by its Euclidean norm, or the
    square root of the sum of the elements squared.
    """
    vabs = np.abs(v)
    signed_vabs = np.sign(np.real(v)) * vabs
    normed_vabs = signed_vabs / np.linalg.norm(signed_vabs)
    return normed_vabs


def normalize_Psi(Psi):
    """
    Normalize a matrix of complex column vectors using
    `normalize_v` on each vector
    """
    normed_Psi = np.zeros(Psi.shape)
    for i in range(Psi.shape[1]):
        v = Psi[:,i]
        normed_Psi[:,i] = normalize_v(v)
    return normed_Psi


def phi_output(A, C):
    eigvals, U = np.linalg.eig(np.asarray(A, dtype=complex))
    angles = np.abs(np.angle(eigvals))
    idx = np.where(
        (np.abs(eigvals) < 1 - 1e-10) & 
        #(np.abs(eigvals) > 0.05) & 
        (np.imag(eigvals) > -1e-12)&
        (angles > 0.02)
        )[0]
    eigvals_sel = eigvals[idx]
    U_sel = U[:, idx]
    V = C @ U_sel
    Phi = normalize_Psi(V)  
    return Phi, eigvals_sel


def periods_from_A(A, dt):
    eigvals = np.linalg.eigvals(A)
    idx = np.abs(eigvals) < 1.0 
    eigvals = eigvals[idx]
    omega = np.abs(np.angle(eigvals)) / dt  # rad/s
    freqs = omega / (2 * np.pi)
    periods = 1 / freqs
    return np.sort(periods)


def save_event_modes_to_csv(event_id, Phi_true, method_modes, method_macs, algos, filename):
    # method_modes: {'srim': Phi_srim, ...}  Phi, shape=(dof, n_modes)
    # method_macs:  {'srim': MAC_srim, ...}  MAC,  shape=(n_modes, n_modes)
    with open(filename, "w", newline='') as f:
        writer = csv.writer(f)
        writer.writerow([f"Event {event_id} True Mode Shapes"])
        for i in range(Phi_true.shape[1]):
            writer.writerow([f"True Mode {i+1}"] + list(Phi_true[:, i]))

        for algo in algos:
            writer.writerow([f"{algo.upper()} Mode Shapes"])
            Phi = method_modes[algo]
            for i in range(Phi.shape[1]):
                writer.writerow([f"{algo.upper()} Mode {i+1}"] + list(Phi[:, i]))

        for algo in algos:
            writer.writerow([f"{algo.upper()} MAC vs True"])
            MAC = method_macs[algo]
            for row in MAC:
                writer.writerow([""] + list(row))
        
        writer.writerow([])  


def plot_q4_max_strain(sr, model, title, html_base):
    """
    sr = model.meta["strain_record"]
    Generate the time history curve of the maximum edge concrete strain/reinforcement strain (nonlinear) or edge strain (elastic).
    """

    t = np.asarray(sr["time"], float)
    cols = model.meta["column_elems"]

    if not sr.get("inelastic", False):
        # ELASTIC: eps_edge = eps0 + kappa*h/2
        h = float(sr.get("section_depth", np.nan))
        stack = []
        for ele in cols:
            eps0  = np.asarray(sr["eps0"][ele],  float)
            kappa = np.asarray(sr["kappa"][ele], float)
            edge  = eps0 + kappa * (h/2.0)
            stack.append(edge)
        edge_max = np.nanmax(np.vstack(stack), axis=0) if stack else np.full_like(t, np.nan)

        fig = go.Figure()
        fig.add_scatter(x=t, y=edge_max, mode="lines", name="Max Edge Strain (elastic)")
        fig.update_layout(title=title, xaxis_title="Time (s)", yaxis_title="Strain")
        fig.write_html(html_base + "_elastic_edge.html", include_plotlyjs="cdn")
        return

    # INELASTIC: concrete edge max & steel max
    conc_stack, steel_stack = [], []
    for ele in cols:
        conc_stack.append(np.asarray(sr["conc_edge_max"][ele], float))
        steel_stack.append(np.asarray(sr["steel_max"][ele],     float))
    conc_max  = np.nanmax(np.vstack(conc_stack),  axis=0) if conc_stack  else np.full_like(t, np.nan)
    steel_max = np.nanmax(np.vstack(steel_stack), axis=0) if steel_stack else np.full_like(t, np.nan)

    f1 = go.Figure(); f2 = go.Figure()
    f1.add_scatter(x=t, y=conc_max,  mode="lines", name="Max Concrete Edge Strain")
    f2.add_scatter(x=t, y=steel_max, mode="lines", name="Max Steel Strain")
    f1.update_layout(title=title+" — Concrete", xaxis_title="Time (s)", yaxis_title="Strain")
    f2.update_layout(title=title+" — Steel",    xaxis_title="Time (s)", yaxis_title="Strain")
    f1.write_html(html_base + "_inelastic_conc.html",  include_plotlyjs="cdn")
    f2.write_html(html_base + "_inelastic_steel.html", include_plotlyjs="cdn")


def save_displacements(displacements, dt, filename):

    nt = len(list(displacements.values())[0])
    time = np.arange(nt) * dt

    nodes = sorted(displacements.keys())

    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)

        # header: time + each node 6 dof
        dof_labels = ["UX", "UY", "UZ", "RX", "RY", "RZ"]
        header = ["time"]
        for n in nodes:
            for lbl in dof_labels:
                header.append(f"node{n}_{lbl}")
        writer.writerow(header)

        # each line: t_k + each node 6DOF
        for k in range(nt):
            row = [time[k]]
            for n in nodes:
                u = displacements[n][k]  # 6
                row.extend(u)
            writer.writerow(row)


def save_strain_stress(stresses, strains, dt, filename):

    nt = len(list(stresses.values())[0])
    time = np.arange(nt) * dt

    elems = sorted(stresses.keys())

    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)

        # header: time + stress + strain
        header = ["time"]
        header += [f"ele{e}_stress" for e in elems]
        header += [f"ele{e}_strain" for e in elems]
        writer.writerow(header)

        # each line: t_k + stress + strain
        for k in range(nt):
            row = [time[k]]
            for e in elems:
                row.append(stresses[e][k])
            for e in elems:
                row.append(strains[e][k])
            writer.writerow(row)


#get damage
def list_event_dirs(case_dir: Path):
    ev_dirs = [p for p in case_dir.iterdir() if p.is_dir() and p.name.isdigit()]
    return sorted(ev_dirs, key=lambda x: int(x.name))

def load_dt(event_dir: Path) -> float:
    p = event_dir / "dt.txt"
    if not p.exists():
        raise FileNotFoundError(f"Missing {p}")
    return float(p.read_text().strip())

def load_inputs(event_dir: Path) -> np.ndarray:
    p = event_dir / "inputs.csv"
    if not p.exists():
        raise FileNotFoundError(f"Missing {p}")
    x = np.loadtxt(p, dtype=float)
    # expected shape (n_in, nt)
    if x.ndim == 1:
        x = x[None, :]
    return x

def load_strain_stress_df(event_dir: Path) -> pd.DataFrame:
    p = event_dir / "strain_stress.csv"
    if not p.exists():
        raise FileNotFoundError(f"Missing {p}")
    return pd.read_csv(p)

def load_freq_vector(event_dir: Path, fname: str) -> np.ndarray:
    p = event_dir / fname
    if not p.exists():
        raise FileNotFoundError(f"Missing {p}")
    f = np.loadtxt(p, dtype=float)
    f = np.atleast_1d(f).astype(float)
    return f

def load_pred_true_processed(event_dir: Path, sid_method: str):
    pred_dir = event_dir / sid_method
    p_true = pred_dir / "outputs_true_processed.csv"
    p_pred = pred_dir / "outputs_pred_processed.csv"
    if not p_true.exists() or not p_pred.exists():
        raise FileNotFoundError(f"Missing processed outputs under {pred_dir}")

    y_true = np.loadtxt(p_true, dtype=float)
    y_pred = np.loadtxt(p_pred, dtype=float)

    # enforce shape (n_out, nt)
    if y_true.ndim == 1:
        y_true = y_true[None, :]
    if y_pred.ndim == 1:
        y_pred = y_pred[None, :]

    if y_true.shape != y_pred.shape:
        raise ValueError(f"Shape mismatch: y_true {y_true.shape}, y_pred {y_pred.shape}")

    return y_true, y_pred


# Baseline selection by input intensity
def compute_intensity(inputs: np.ndarray, metric: str) -> float:
    """
    inputs: (n_in, nt)
    metric:
      - "pga": max over channels of max(abs(input))
      - "rms": max over channels of rms(input)
    """
    if metric == "pga":
        return float(np.max(np.abs(inputs)))
    if metric == "rms":
        rms_each = np.sqrt(np.mean(inputs**2, axis=1))
        return float(np.max(rms_each))
    raise ValueError("BASELINE_METRIC must be 'pga' or 'rms'")

def select_baseline_events(case_dir: Path, n_baseline: int, metric: str):
    ev_dirs = list_event_dirs(case_dir)
    rows = []
    for ev_dir in ev_dirs:
        ev = int(ev_dir.name)
        inputs = load_inputs(ev_dir)
        inten = compute_intensity(inputs, metric)
        rows.append({"event": ev, "intensity": inten})
    df_int = pd.DataFrame(rows).sort_values("intensity").reset_index(drop=True)
    baseline_ids = df_int.loc[: n_baseline - 1, "event"].tolist()
    return baseline_ids, df_int

# Metric computations
def compute_ksec_for_element(df: pd.DataFrame, ele_id: int, eps_stab: float = 1e-12) -> float:
    s_col = f"ele{ele_id}_stress"
    e_col = f"ele{ele_id}_strain"
    if s_col not in df.columns or e_col not in df.columns:
        raise KeyError(f"Missing columns {s_col} or {e_col} in strain_stress.csv")

    stress = df[s_col].to_numpy(dtype=float)
    strain = df[e_col].to_numpy(dtype=float)

    idx = int(np.argmax(np.abs(stress)))
    sigma = float(stress[idx])
    eps = float(strain[idx])
    

    return abs(sigma) / (abs(eps) + eps_stab)

def compute_kref_ele(case_dir: Path, baseline_ids, elements) -> dict:
    """
    For each element:
      kref_ele = median over baseline events of ksec_ele
    """
    kref_ele = {}
    for ele in elements:
        k_list = []
        for ev in baseline_ids:
            ev_dir = case_dir / str(ev)
            df_ss = load_strain_stress_df(ev_dir)
            k_list.append(compute_ksec_for_element(df_ss, ele))
        kref_ele[ele] = float(np.median(np.asarray(k_list, dtype=float)))
    return kref_ele

def compute_Dk_event(df_ss: pd.DataFrame, elements, kref_ele: dict, eps_stab: float = 1e-12) -> dict:
    """
    Per event:
      - compute ksec for each element
      - compute Dk_ele = 1 - ksec_ele/kref_ele
      - aggregate Dk_event = median(Dk_ele across elements)
    """
    out = {}
    dk_list = []
    for ele in elements:
        ksec = compute_ksec_for_element(df_ss, ele)
        kref = float(kref_ele[ele])
        dk = 1.0 - (ksec / (kref + eps_stab))
        out[f"ksec_ele{ele}"] = float(ksec)
        out[f"Dk_ele{ele}"] = float(dk)
        dk_list.append(dk)
    out["Dk_median"] = float(np.median(np.asarray(dk_list, dtype=float)))
    return out

def compute_fbase_per_mode(case_dir: Path, baseline_ids, freq_file: str) -> np.ndarray:
    """
    Baseline frequency per mode:
      fbase_modei = median over baseline events of f_event_modei
    """
    f_mat = []
    for ev in baseline_ids:
        ev_dir = case_dir / str(ev)
        f_vec = load_freq_vector(ev_dir, freq_file)
        if f_vec.size < 3:
            raise ValueError(f"{ev_dir/freq_file} has <3 modes")
        f_mat.append(f_vec[:3])
    f_mat = np.vstack(f_mat).astype(float)  # (n_base, 3)
    return np.median(f_mat, axis=0)

def compute_Df_event(f_event: np.ndarray, fbase_per_mode: np.ndarray, eps_stab: float = 1e-12) -> dict:
    """
    Per event:
      - Df_modei = 1 - f_event_i / fbase_i
      - Df_median = median(Df_mode1..3)
    """
    if f_event.size < 3:
        raise ValueError(f"Expected 3 modes, got {f_event.size}")
    if fbase_per_mode.size < 3:
        raise ValueError(f"Expected 3 baseline modes, got {fbase_per_mode.size}")

    f_event = f_event[:3].astype(float)
    fbase = fbase_per_mode[:3].astype(float)

    df_modes = 1.0 - (f_event / (fbase + eps_stab))
    return {
        "f1_event": float(f_event[0]),
        "f2_event": float(f_event[1]),
        "f3_event": float(f_event[2]),
        "f1_base": float(fbase[0]),
        "f2_base": float(fbase[1]),
        "f3_base": float(fbase[2]),
        "Df_mode1": float(df_modes[0]),
        "Df_mode2": float(df_modes[1]),
        "Df_mode3": float(df_modes[2]),
        "Df_median": float(np.median(df_modes)),
    }

def compute_Dr_residual_tail(y_true: np.ndarray, y_pred: np.ndarray, dt: float, tail_sec: float) -> dict:
    
    nt = y_true.shape[1]
    k_tail = int(round(tail_sec / dt))
    k_tail = max(1, min(k_tail, nt))

    y_true_tail = y_true[:, -k_tail:]
    y_pred_tail = y_pred[:, -k_tail:]

    
    res = np.mean(np.abs(y_true_tail), axis=1)

    out = {
        "Dr_tail_sec": float(tail_sec),
        "Dr_tail_samples": int(k_tail),
        "Dr_residual_mean": float(np.mean(res)),
        "Dr_residual_max": float(np.max(res)),
    }
    for i, val in enumerate(res, start=1):
        out[f"Dr_residual_ch{i}"] = float(val)
    return out


def apply_load_bridge_model_multi_support(
    model,
    inputs: np.ndarray,
    dt: float,
    node_channel_map: dict,
    input_channels: list,
    *,
    factor: float = 1.0,
    pattern_tag: int = 20,
    ts_tag_start: int = 2000,
    gm_tag_start: int = 3000,
):
    
    if inputs is None or dt is None:
        raise ValueError("Missing inputs or dt.")
    if inputs.ndim != 2:
        raise ValueError(f"inputs must be 2D (n_channels, nt). Got {inputs.shape}")

    # Build mapping: channel number -> row index in inputs
    ch_to_row = {ch: k for k, ch in enumerate(input_channels)}

    model.pattern("MultipleSupportExcitation", pattern_tag)

    ts_tag = ts_tag_start
    gm_tag = gm_tag_start

    for node, (chx, chy) in node_channel_map.items():
        if chx not in ch_to_row or chy not in ch_to_row:
            raise ValueError(
                f"Node {node} requests channels ({chx},{chy}), "
                f"but input_channels={input_channels}."
            )

        ix = ch_to_row[chx]
        iy = ch_to_row[chy]

        # 1) timeSeries for this support in X and Y
        ts_x = ts_tag; ts_tag += 1
        ts_y = ts_tag; ts_tag += 1
        model.timeSeries("Path", ts_x, values=inputs[ix].tolist(), dt=dt, factor=factor)
        model.timeSeries("Path", ts_y, values=inputs[iy].tolist(), dt=dt, factor=factor)

        # 2) GroundMotion objects
        gm_x = gm_tag; gm_tag += 1
        gm_y = gm_tag; gm_tag += 1
        model.groundMotion(gm_x, "Plain", accel=ts_x)
        model.groundMotion(gm_y, "Plain", accel=ts_y)

        # 3) imposed motions (DOF 1=X, DOF 2=Y)
        model.imposedMotion(node, 1, gm_x)
        model.imposedMotion(node, 2, gm_y)
    return model
