import xara
import xara.units.iks as units
import numpy as np
import math
from models.analysis import apply_damping

def ReinforcedRectangle(model, id, h, b, cover, coreID, coverID, steelID, numBars, barArea, nfCoreY, nfCoreZ, nfCoverY, nfCoverZ, GJ):
    r"""
    Define a procedure which generates a rectangular reinforced concrete section
    with one layer of steel evenly distributed around the perimeter and a confined core.

                          y
                          |
                          |
                          |
                ---------------------
                |\                 /|
                | \---------------/ |
                | |               | |
                | |               | |
     z ---------| |               | |  h
                | |               | |
                | |               | |
                | /---------------\ |
                |/                 \|
                ---------------------
                          b

    Arguments
       id - tag for the section that is generated by this procedure
       h - overall height of the section (see above)
       b - overall width of the section (see above)
       cover - thickness of the cover patches
       coreID - material tag for the core patch
       coverID - material tag for the cover patches
       steelID - material tag for the reinforcing steel
       numBars - number of reinforcing bars on any given side of the section
       barArea - cross-sectional area of each reinforcing bar
       nfCoreY - number of fibers in the core patch in the y direction
       nfCoreZ - number of fibers in the core patch in the z direction
       nfCoverY - number of fibers in the cover patches with long sides in the y direction
       nfCoverZ - number of fibers in the cover patches with long sides in the z direction

    Notes
       The thickness of cover concrete is constant on all sides of the core.
       The number of bars is the same on any given side of the section.
       The reinforcing bars are all the same size.
       The number of fibers in the short direction of the cover patches is set to 1.

    Written: Andreas Schellenberg (andreas.schellenberg@gmail.com)
    Date: June 2017
    """

    # The distance from the section z-axis to the edge of the cover concrete
    # in the positive y direction
    coverY = h/2.0

    # The distance from the section y-axis to the edge of the cover concrete
    # in the positive z direction
    coverZ = b/2.0

    # Determine the corresponding values from the respective axes to the
    # edge of the core concrete
    coreY = coverY - cover
    coreZ = coverZ - cover

    # Define the fiber section
    model.section("Fiber", id, GJ=GJ)

    # Define the core patch
    model.patch("quad", coreID, nfCoreZ, nfCoreY, -coreY, coreZ, -coreY, -coreZ, coreY, -coreZ, coreY, coreZ)

    # Define the four cover patches
    model.patch("quad", coverID, 1,        nfCoverY, -coverY,  coverZ, -coreY,   coreZ,   coreY,   coreZ,   coverY,  coverZ)
    model.patch("quad", coverID, 1,        nfCoverY, -coreY,  -coreZ,  -coverY, -coverZ,  coverY, -coverZ,  coreY,  -coreZ)
    model.patch("quad", coverID, nfCoverZ, 1,        -coverY,  coverZ, -coverY, -coverZ, -coreY,  -coreZ,  -coreY,   coreZ)
    model.patch("quad", coverID, nfCoverZ, 1,         coreY,   coreZ,   coreY,  -coreZ,   coverY, -coverZ,  coverY,  coverZ)

    # Define the steel along constant values of y (in the z direction)
    model.layer("straight", steelID, numBars, barArea, -coreY, coreZ, -coreY, -coreZ)
    model.layer("straight", steelID, numBars, barArea,  coreY, coreZ,  coreY, -coreZ)

    # Determine the spacing for the remaining bars in the y direction
    spacingY = (2.0*coreY)/(numBars-1)

    # Avoid double counting bars
    numBars = numBars-2

    # Define remaining steel in the y direction
    model.layer("straight", steelID, numBars, barArea, coreY-spacingY,  coreZ, (-coreY+spacingY),  coreZ)
    model.layer("straight", steelID, numBars, barArea, coreY-spacingY, -coreZ, (-coreY+spacingY), -coreZ)


def create_frame(elastic:bool,
                multisupport:bool,
                verbose = False):

    # create Model in three-dimensions with 6 DOF/node
    model = xara.Model(ndm=3, ndf=6)

    # Geometry and Material Properties
        # Nodes(location)
        # Boundary conditions(nodes)
        # Elements(nodes, material properties,                             geometric transformation)
                          # non-fiber section elastic (linear)              # linear
                          # fiber section (linear elastic OR inelastic)     # PDelta
                                                                            # corotational

    # Geometry
    # ---------------

    # Set parameters for model geometry
    h  = 82.0;      # Story height 82 144
    by = 96.0;      # Bay width in Y-direction 96 240
    bx = 72.0;      # Bay width in X-direction 72 240

    # Create nodes
    #            tag    X        Y       Z 
    model.node( 1, (-bx/2.0,  by/2.0,   0.0))
    model.node( 2, ( bx/2.0,  by/2.0,   0.0))
    model.node( 3, ( bx/2.0, -by/2.0,   0.0))
    model.node( 4, (-bx/2.0, -by/2.0,   0.0))

    model.node( 5, (-bx/2.0,  by/2.0,     h))
    model.node( 6, ( bx/2.0,  by/2.0,     h))
    model.node( 7, ( bx/2.0, -by/2.0,     h))
    model.node( 8, (-bx/2.0, -by/2.0,     h))

    model.node(10, (-bx/2.0,  by/2.0, 2.0*h))
    model.node(11, ( bx/2.0,  by/2.0, 2.0*h))
    model.node(12, ( bx/2.0, -by/2.0, 2.0*h))
    model.node(13, (-bx/2.0, -by/2.0, 2.0*h))

    model.node(15, (-bx/2.0,  by/2.0, 3.0*h))
    model.node(16, ( bx/2.0,  by/2.0, 3.0*h))
    model.node(17, ( bx/2.0, -by/2.0, 3.0*h))
    model.node(18, (-bx/2.0, -by/2.0, 3.0*h))


    # Set base constraints
    #      tag DX DY DZ RX RY RZ
    model.fix(1, (1, 1, 1, 1, 1, 1))
    model.fix(2, (1, 1, 1, 1, 1, 1))
    model.fix(3, (1, 1, 1, 1, 1, 1))
    model.fix(4, (1, 1, 1, 1, 1, 1))


    # Define materials for nonlinear columns
    # --------------------------------------
    # CONCRETE
    fc = 4.0 # unconfined
    fpc = 5.0 # confined
    Ec = 57000.0*math.sqrt(fc*1000.0)/1000.0
    if not elastic:
        # Core concrete (confined)
        #                                 tag  f'c   epsc0  f'cu  epscu
        model.uniaxialMaterial("Concrete01", 1, -fpc, -2*fpc/Ec, -3.5, -0.02)
        # Cover concrete (unconfined)
        #                                 tag  f'c   epsc0  f'cu  epscu
        model.uniaxialMaterial("Concrete01", 2, -fc, -2*fc/Ec, 0.0, -0.006)
    else:
        # Core concrete
        model.uniaxialMaterial("Elastic", 1, Ec)
        # Cover concrete
        model.uniaxialMaterial("Elastic", 2, Ec)

    # STEEL
    fy = 60.0;       # Yield stress
    Es = 30000.0;    # Young's modulus
    # Reinforcing steel 
    if not elastic:
        #                                tag fy  E0  b
        model.uniaxialMaterial("Steel01", 3, fy, Es, 0.02)
    else:
        model.uniaxialMaterial("Elastic", 3, Es)


    # Define column elements
    # ----------------------
    # Column parameters
    h_col  = 20.0
    b_col = 20.0
    GJ = 1.0E10
    colSec = 1
    beamSec = 2

    ReinforcedRectangle(model, colSec,
                        h=h_col, 
                        b=b_col,
                        cover=2.5, 
                        coreID=1,
                        coverID=2,
                        steelID=3,
                        numBars=3,
                        barArea=0.79,
                        nfCoreY=8,      
                        nfCoreZ=8,      
                        nfCoverY=10,      
                        nfCoverZ=10,
                        GJ=GJ)
    # Number of column integration points (sections)
    itg_col = 1
    npts_col = 4
    model.beamIntegration("Lobatto", itg_col, colSec, npts_col)
        
    # Geometric transformation for columns
    colTransf = 1
    model.geomTransf("Linear", colTransf, (1.0, 0.0, 0.0))

    #                                tag ndI ndJ transfTag integrationTag
    model.element("forceBeamColumn",  1, ( 1,  5), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  2, ( 2,  6), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  3, ( 3,  7), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  4, ( 4,  8), transform=colTransf, section=colSec, shear=0)

    model.element("forceBeamColumn",  5, ( 5, 10), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  6, ( 6, 11), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  7, ( 7, 12), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn",  8, ( 8, 13), transform=colTransf, section=colSec, shear=0)

    model.element("forceBeamColumn",  9, (10, 15), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn", 10, (11, 16), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn", 11, (12, 17), transform=colTransf, section=colSec, shear=0)
    model.element("forceBeamColumn", 12, (13, 18), transform=colTransf, section=colSec, shear=0)

    # Define beam elements
    # --------------------

    # Define material properties for elastic beams
    # Using beam depth of 24 and width of 18
    Abeam = 18.0*24.0
    # Second moments of area
    Ibeamzz = 1.0/12.0*18.0*pow(24.0,3)
    Ibeamyy = 1.0/12.0*24.0*pow(18.0,3)
    Jbeam = Ibeamzz + Ibeamyy

    nu = 0.2
    Gb = Ec/(2 * (1 + nu))

    # Define elastic section for beams
    #                       tag     E    A      Iz       Iy     G    J
    model.section("Elastic", beamSec, Ec, Abeam, Ibeamzz, Ibeamyy, Gb, Jbeam)

    # Geometric transformation for beams
    beamTransf = 2
    model.geomTransf("Linear", beamTransf, 0.0, 0.0, 1.0)

    # Create the beam elements
    #                   tag (ndI ndJ) transfTag integrationTag
    model.element("elasticBeamColumn", 13, ( 5,  6), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 14, ( 6,  7), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 15, ( 7,  8), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 16, ( 8,  5), transform=beamTransf, section=beamSec, shear=0)

    model.element("elasticBeamColumn", 17, (10, 11), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 18, (11, 12), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 19, (12, 13), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 20, (13, 10), transform=beamTransf, section=beamSec, shear=0)

    model.element("elasticBeamColumn", 21, (15, 16), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 22, (16, 17), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 23, (17, 18), transform=beamTransf, section=beamSec, shear=0)
    model.element("elasticBeamColumn", 24, (18, 15), transform=beamTransf, section=beamSec, shear=0)

    # Lumped mass at nodes on top of columns
    # 10% of axial column capacity assuming unconfined concrete
    p = 0.1*fc*b_col*h_col
    m = p/units.gravity
    #         tag   MX MY MZ   RX   RY   RZ
    model.mass( 5, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 6, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 7, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 8, (m, m, m, 0.0, 0.0, 0.0))

    model.mass( 10, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 11, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 12, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 13, (m, m, m, 0.0, 0.0, 0.0))

    model.mass( 15, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 16, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 17, (m, m, m, 0.0, 0.0, 0.0))
    model.mass( 18, (m, m, m, 0.0, 0.0, 0.0))

    # set rayleigh damping factors
    # model.rayleigh(0.0319, 0.0, 0.0125, 0.0)
    apply_damping(model=model, zeta=[0.03, 0.03], verbose=verbose)

    return model


def apply_load_frame(model, inputx=None, inputy=None, dt=None):
    """
    Add dynamic loads to frame model
    """
    if np.all(inputx is None) or np.all(inputy is None) or dt is None:
        raise ValueError("Missing inputx, inputy, or dt. Exiting.")
    
    # Define earthquake excitation
    # ----------------------------
    # Set up the acceleration records for fault normal (x, dof 1) and fault parallel (y, dof 2)
    model.timeSeries("Path", 2, values=inputx.tolist(), dt=dt, factor=1.0)
    model.timeSeries("Path", 3, values=inputy.tolist(), dt=dt, factor=1.0)

    # Define the excitation using the given ground motion records
    #                         tag dir         accel series args
    model.pattern("UniformExcitation", 2, 1, accel=2)
    model.pattern("UniformExcitation", 3, 2, accel=3)

    return model



